name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: macos-10.15
  #  runs-on: ubuntu-latest # need to use linux if we want to use the linter

    steps:
    - uses: actions/checkout@v2

    # Run Linter against code base, see https://github.com/github/super-linter for how the linter works
    - name: Lint Code Base
      if: ${{ runner.os == 'Linux'}}
      uses: docker://github/super-linter:v2.0.0
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_MD: true

    - name: Run tests
      if: ${{ github.base_ref == 'master' }}
      run: echo Github Actions template

